-- TESTE

-- END TESTE

INSERT INTO nomes_masculinos(nome) VALUES('Achilles');
INSERT INTO nomes_masculinos(nome) VALUES('Adonis');
INSERT INTO nomes_masculinos(nome) VALUES('Ajax');
INSERT INTO nomes_masculinos(nome) VALUES('Anastasios');
INSERT INTO nomes_masculinos(nome) VALUES('Andreas');
INSERT INTO nomes_masculinos(nome) VALUES('Antonios');
INSERT INTO nomes_masculinos(nome) VALUES('Apollo');
INSERT INTO nomes_masculinos(nome) VALUES('Argus');
INSERT INTO nomes_masculinos(nome) VALUES('Aristotle');
INSERT INTO nomes_masculinos(nome) VALUES('Atlas');
INSERT INTO nomes_masculinos(nome) VALUES('Basil');
INSERT INTO nomes_masculinos(nome) VALUES('Cassander');
INSERT INTO nomes_masculinos(nome) VALUES('Damon');
INSERT INTO nomes_masculinos(nome) VALUES('Dimitrios');
INSERT INTO nomes_masculinos(nome) VALUES('Eros');
INSERT INTO nomes_masculinos(nome) VALUES('Evander');
INSERT INTO nomes_masculinos(nome) VALUES('Hector');
INSERT INTO nomes_masculinos(nome) VALUES('Hermes');
INSERT INTO nomes_masculinos(nome) VALUES('Icarus');
INSERT INTO nomes_masculinos(nome) VALUES('Kyros');
INSERT INTO nomes_masculinos(nome) VALUES('Leander');
INSERT INTO nomes_masculinos(nome) VALUES('Leonidas');
INSERT INTO nomes_masculinos(nome) VALUES('Midas');
INSERT INTO nomes_masculinos(nome) VALUES('Nestor');
INSERT INTO nomes_masculinos(nome) VALUES('Odysseus');
INSERT INTO nomes_masculinos(nome) VALUES('Orpheus');
INSERT INTO nomes_masculinos(nome) VALUES('Pallas');
INSERT INTO nomes_masculinos(nome) VALUES('Paris');
INSERT INTO nomes_masculinos(nome) VALUES('Perseus');
INSERT INTO nomes_masculinos(nome) VALUES('Phoenix');
INSERT INTO nomes_masculinos(nome) VALUES('Plato');
INSERT INTO nomes_masculinos(nome) VALUES('Pyrrhus');
INSERT INTO nomes_masculinos(nome) VALUES('Rhodes');
INSERT INTO nomes_masculinos(nome) VALUES('Socrates');
INSERT INTO nomes_masculinos(nome) VALUES('Solon');
INSERT INTO nomes_masculinos(nome) VALUES('Thaddeus');
INSERT INTO nomes_masculinos(nome) VALUES('Theo');
INSERT INTO nomes_masculinos(nome) VALUES('Titan');
INSERT INTO nomes_masculinos(nome) VALUES('Xander');
INSERT INTO nomes_masculinos(nome) VALUES('Xenon');
INSERT INTO nomes_masculinos(nome) VALUES('Zenon');
INSERT INTO nomes_masculinos(nome) VALUES('Alexios');
INSERT INTO nomes_masculinos(nome) VALUES('Cleon');
INSERT INTO nomes_masculinos(nome) VALUES('Damian');
INSERT INTO nomes_masculinos(nome) VALUES('Evangelos');
INSERT INTO nomes_masculinos(nome) VALUES('Gregorios');
INSERT INTO nomes_masculinos(nome) VALUES('Ilias');
INSERT INTO nomes_masculinos(nome) VALUES('Lucian');
INSERT INTO nomes_masculinos(nome) VALUES('Marios');
INSERT INTO nomes_masculinos(nome) VALUES('Nikos');
INSERT INTO nomes_masculinos(nome) VALUES('Agamemnon');
INSERT INTO nomes_masculinos(nome) VALUES('Alcibiades');
INSERT INTO nomes_masculinos(nome) VALUES('Anaxagoras');
INSERT INTO nomes_masculinos(nome) VALUES('Antigonus');
INSERT INTO nomes_masculinos(nome) VALUES('Archelaus');
INSERT INTO nomes_masculinos(nome) VALUES('Aristarchus');
INSERT INTO nomes_masculinos(nome) VALUES('Aristides');
INSERT INTO nomes_masculinos(nome) VALUES('Aristophanes');
INSERT INTO nomes_masculinos(nome) VALUES('Artaxerxes');
INSERT INTO nomes_masculinos(nome) VALUES('Astyages');
INSERT INTO nomes_masculinos(nome) VALUES('Bardiya');
INSERT INTO nomes_masculinos(nome) VALUES('Cambyses');
INSERT INTO nomes_masculinos(nome) VALUES('Cyrus');
INSERT INTO nomes_masculinos(nome) VALUES('Darius');
INSERT INTO nomes_masculinos(nome) VALUES('Datis');
INSERT INTO nomes_masculinos(nome) VALUES('Demetrius');
INSERT INTO nomes_masculinos(nome) VALUES('Ephialtes');
INSERT INTO nomes_masculinos(nome) VALUES('Epictetus');
INSERT INTO nomes_masculinos(nome) VALUES('Euripides');
INSERT INTO nomes_masculinos(nome) VALUES('Gordias');
INSERT INTO nomes_masculinos(nome) VALUES('Heraclitus');
INSERT INTO nomes_masculinos(nome) VALUES('Herodotus');
INSERT INTO nomes_masculinos(nome) VALUES('Hippocrates');
INSERT INTO nomes_masculinos(nome) VALUES('Isocrates');
INSERT INTO nomes_masculinos(nome) VALUES('Leonidas');
INSERT INTO nomes_masculinos(nome) VALUES('Lycurgus');
INSERT INTO nomes_masculinos(nome) VALUES('Miltiades');
INSERT INTO nomes_masculinos(nome) VALUES('Minos');
INSERT INTO nomes_masculinos(nome) VALUES('Nicias');
INSERT INTO nomes_masculinos(nome) VALUES('Parmenides');
INSERT INTO nomes_masculinos(nome) VALUES('Pausanias');
INSERT INTO nomes_masculinos(nome) VALUES('Pericles');
INSERT INTO nomes_masculinos(nome) VALUES('Phidias');
INSERT INTO nomes_masculinos(nome) VALUES('Ptolemy');
INSERT INTO nomes_masculinos(nome) VALUES('Pythagoras');
INSERT INTO nomes_masculinos(nome) VALUES('Socrates');
INSERT INTO nomes_masculinos(nome) VALUES('Solon');
INSERT INTO nomes_masculinos(nome) VALUES('Sophonias');
INSERT INTO nomes_masculinos(nome) VALUES('Spartacus');
INSERT INTO nomes_masculinos(nome) VALUES('Strabo');
INSERT INTO nomes_masculinos(nome) VALUES('Themistocles');
INSERT INTO nomes_masculinos(nome) VALUES('Theocritus');
INSERT INTO nomes_masculinos(nome) VALUES('Thucydides');
INSERT INTO nomes_masculinos(nome) VALUES('Timon');
INSERT INTO nomes_masculinos(nome) VALUES('Xerxes');
INSERT INTO nomes_masculinos(nome) VALUES('Xanthippus');
INSERT INTO nomes_masculinos(nome) VALUES('Zeno');
INSERT INTO nomes_masculinos(nome) VALUES('Abel');
INSERT INTO nomes_masculinos(nome) VALUES('Arash');
INSERT INTO nomes_masculinos(nome) VALUES('Ardashir');
INSERT INTO nomes_masculinos(nome) VALUES('Arezou');
INSERT INTO nomes_masculinos(nome) VALUES('Bahram');
INSERT INTO nomes_masculinos(nome) VALUES('Barbad');
INSERT INTO nomes_masculinos(nome) VALUES('Behzad');
INSERT INTO nomes_masculinos(nome) VALUES('Bijan');
INSERT INTO nomes_masculinos(nome) VALUES('Dariush');
INSERT INTO nomes_masculinos(nome) VALUES('Darab');
INSERT INTO nomes_masculinos(nome) VALUES('Farhad');
INSERT INTO nomes_masculinos(nome) VALUES('Farshad');
INSERT INTO nomes_masculinos(nome) VALUES('Fereydoun');
INSERT INTO nomes_masculinos(nome) VALUES('Giv');
INSERT INTO nomes_masculinos(nome) VALUES('Gordafarid');
INSERT INTO nomes_masculinos(nome) VALUES('Homayoun');
INSERT INTO nomes_masculinos(nome) VALUES('Hormoz');
INSERT INTO nomes_masculinos(nome) VALUES('Houshang');
INSERT INTO nomes_masculinos(nome) VALUES('Jamsheed');
INSERT INTO nomes_masculinos(nome) VALUES('Jamshid');
INSERT INTO nomes_masculinos(nome) VALUES('Kaveh');
INSERT INTO nomes_masculinos(nome) VALUES('Kayvan');
INSERT INTO nomes_masculinos(nome) VALUES('Khosrow');
INSERT INTO nomes_masculinos(nome) VALUES('Lohrasp');
INSERT INTO nomes_masculinos(nome) VALUES('Maziar');
INSERT INTO nomes_masculinos(nome) VALUES('Mehrdad');
INSERT INTO nomes_masculinos(nome) VALUES('Mithra');
INSERT INTO nomes_masculinos(nome) VALUES('Nader');
INSERT INTO nomes_masculinos(nome) VALUES('Nasrin');
INSERT INTO nomes_masculinos(nome) VALUES('Navid');
INSERT INTO nomes_masculinos(nome) VALUES('Nezam');
INSERT INTO nomes_masculinos(nome) VALUES('Nushin');
INSERT INTO nomes_masculinos(nome) VALUES('Parviz');
INSERT INTO nomes_masculinos(nome) VALUES('Ramin');
INSERT INTO nomes_masculinos(nome) VALUES('Rashid');
INSERT INTO nomes_masculinos(nome) VALUES('Rostam');
INSERT INTO nomes_masculinos(nome) VALUES('Sam');
INSERT INTO nomes_masculinos(nome) VALUES('Shahram');
INSERT INTO nomes_masculinos(nome) VALUES('Shapur');
INSERT INTO nomes_masculinos(nome) VALUES('Soroush');
INSERT INTO nomes_masculinos(nome) VALUES('Sohrab');
INSERT INTO nomes_masculinos(nome) VALUES('Tahmuras');
INSERT INTO nomes_masculinos(nome) VALUES('Vahid');
INSERT INTO nomes_masculinos(nome) VALUES('Vash');
INSERT INTO nomes_masculinos(nome) VALUES('Yazdegerd');
INSERT INTO nomes_masculinos(nome) VALUES('Zahhak');
INSERT INTO nomes_masculinos(nome) VALUES('Zal');
INSERT INTO nomes_masculinos(nome) VALUES('Zartosht');

INSERT INTO nomes_femininos(nome) VALUES('Ariadne');
INSERT INTO nomes_femininos(nome) VALUES('Athena');
INSERT INTO nomes_femininos(nome) VALUES('Calliope');
INSERT INTO nomes_femininos(nome) VALUES('Cassandra');
INSERT INTO nomes_femininos(nome) VALUES('Chloe');
INSERT INTO nomes_femininos(nome) VALUES('Cleo');
INSERT INTO nomes_femininos(nome) VALUES('Danae');
INSERT INTO nomes_femininos(nome) VALUES('Daphne');
INSERT INTO nomes_femininos(nome) VALUES('Demetria');
INSERT INTO nomes_femininos(nome) VALUES('Electra');
INSERT INTO nomes_femininos(nome) VALUES('Elena');
INSERT INTO nomes_femininos(nome) VALUES('Eudora');
INSERT INTO nomes_femininos(nome) VALUES('Eugenia');
INSERT INTO nomes_femininos(nome) VALUES('Eunice');
INSERT INTO nomes_femininos(nome) VALUES('Eurydice');
INSERT INTO nomes_femininos(nome) VALUES('Gaia');
INSERT INTO nomes_femininos(nome) VALUES('Helen');
INSERT INTO nomes_femininos(nome) VALUES('Hermione');
INSERT INTO nomes_femininos(nome) VALUES('Hestia');
INSERT INTO nomes_femininos(nome) VALUES('Io');
INSERT INTO nomes_femininos(nome) VALUES('Irene');
INSERT INTO nomes_femininos(nome) VALUES('Ismene');
INSERT INTO nomes_femininos(nome) VALUES('Leda');
INSERT INTO nomes_femininos(nome) VALUES('Lydia');
INSERT INTO nomes_femininos(nome) VALUES('Maia');
INSERT INTO nomes_femininos(nome) VALUES('Melina');
INSERT INTO nomes_femininos(nome) VALUES('Melpomene');
INSERT INTO nomes_femininos(nome) VALUES('Nephele');
INSERT INTO nomes_femininos(nome) VALUES('Nerissa');
INSERT INTO nomes_femininos(nome) VALUES('Nyx');
INSERT INTO nomes_femininos(nome) VALUES('Olympia');
INSERT INTO nomes_femininos(nome) VALUES('Pandora');
INSERT INTO nomes_femininos(nome) VALUES('Penelope');
INSERT INTO nomes_femininos(nome) VALUES('Persephone');
INSERT INTO nomes_femininos(nome) VALUES('Phoebe');
INSERT INTO nomes_femininos(nome) VALUES('Psyche');
INSERT INTO nomes_femininos(nome) VALUES('Rhea');
INSERT INTO nomes_femininos(nome) VALUES('Selene');
INSERT INTO nomes_femininos(nome) VALUES('Sophia');
INSERT INTO nomes_femininos(nome) VALUES('Theia');
INSERT INTO nomes_femininos(nome) VALUES('Themis');
INSERT INTO nomes_femininos(nome) VALUES('Thalia');
INSERT INTO nomes_femininos(nome) VALUES('Xanthe');
INSERT INTO nomes_femininos(nome) VALUES('Zoe');
INSERT INTO nomes_femininos(nome) VALUES('Andromeda');
INSERT INTO nomes_femininos(nome) VALUES('Anastasia');
INSERT INTO nomes_femininos(nome) VALUES('Calista');
INSERT INTO nomes_femininos(nome) VALUES('Charis');
INSERT INTO nomes_femininos(nome) VALUES('Cora');
INSERT INTO nomes_femininos(nome) VALUES('Desdemona');
INSERT INTO nomes_femininos(nome) VALUES('Elektra');
INSERT INTO nomes_femininos(nome) VALUES('Eleni');
INSERT INTO nomes_femininos(nome) VALUES('Eudoxia');
INSERT INTO nomes_femininos(nome) VALUES('Eunomia');
INSERT INTO nomes_femininos(nome) VALUES('Galatea');
INSERT INTO nomes_femininos(nome) VALUES('Helena');
INSERT INTO nomes_femininos(nome) VALUES('Hera');
INSERT INTO nomes_femininos(nome) VALUES('Ianthe');
INSERT INTO nomes_femininos(nome) VALUES('Isidora');
INSERT INTO nomes_femininos(nome) VALUES('Kalliope');
INSERT INTO nomes_femininos(nome) VALUES('Kassandra');
INSERT INTO nomes_femininos(nome) VALUES('Kyra');
INSERT INTO nomes_femininos(nome) VALUES('Lysandra');
INSERT INTO nomes_femininos(nome) VALUES('Megara');
INSERT INTO nomes_femininos(nome) VALUES('Medea');
INSERT INTO nomes_femininos(nome) VALUES('Nicolette');
INSERT INTO nomes_femininos(nome) VALUES('Nike');
INSERT INTO nomes_femininos(nome) VALUES('Ophelia');
INSERT INTO nomes_femininos(nome) VALUES('Ourania');
INSERT INTO nomes_femininos(nome) VALUES('Parthenia');
INSERT INTO nomes_femininos(nome) VALUES('Alma');
INSERT INTO nomes_femininos(nome) VALUES('Polyxena');
INSERT INTO nomes_femininos(nome) VALUES('Selena');
INSERT INTO nomes_femininos(nome) VALUES('Seraphina');
INSERT INTO nomes_femininos(nome) VALUES('Sylvia');
INSERT INTO nomes_femininos(nome) VALUES('Thais');
INSERT INTO nomes_femininos(nome) VALUES('Theodora');
INSERT INTO nomes_femininos(nome) VALUES('Urania');
INSERT INTO nomes_femininos(nome) VALUES('Vasiliki');
INSERT INTO nomes_femininos(nome) VALUES('Xenia');
INSERT INTO nomes_femininos(nome) VALUES('Zina');
INSERT INTO nomes_femininos(nome) VALUES('Azar');
INSERT INTO nomes_femininos(nome) VALUES('Bahareh');
INSERT INTO nomes_femininos(nome) VALUES('Banu');
INSERT INTO nomes_femininos(nome) VALUES('Daria');
INSERT INTO nomes_femininos(nome) VALUES('Delara');
INSERT INTO nomes_femininos(nome) VALUES('Donya');
INSERT INTO nomes_femininos(nome) VALUES('Elham');
INSERT INTO nomes_femininos(nome) VALUES('Farnaz');
INSERT INTO nomes_femininos(nome) VALUES('Jaleh');
INSERT INTO nomes_femininos(nome) VALUES('Kiana');
INSERT INTO nomes_femininos(nome) VALUES('Ladan');
INSERT INTO nomes_femininos(nome) VALUES('Leila');
INSERT INTO nomes_femininos(nome) VALUES('Lila');
INSERT INTO nomes_femininos(nome) VALUES('Mahsa');
INSERT INTO nomes_femininos(nome) VALUES('Mahnaz');
INSERT INTO nomes_femininos(nome) VALUES('Marjan');
INSERT INTO nomes_femininos(nome) VALUES('Maryam');
INSERT INTO nomes_femininos(nome) VALUES('Mina');
INSERT INTO nomes_femininos(nome) VALUES('Nadia');
INSERT INTO nomes_femininos(nome) VALUES('Nazanin');
INSERT INTO nomes_femininos(nome) VALUES('Negin');
INSERT INTO nomes_femininos(nome) VALUES('Pari');
INSERT INTO nomes_femininos(nome) VALUES('Parisa');
INSERT INTO nomes_femininos(nome) VALUES('Raha');
INSERT INTO nomes_femininos(nome) VALUES('Sahar');
INSERT INTO nomes_femininos(nome) VALUES('Samira');
INSERT INTO nomes_femininos(nome) VALUES('Sepideh');
INSERT INTO nomes_femininos(nome) VALUES('Shadi');
INSERT INTO nomes_femininos(nome) VALUES('Shahnaz');
INSERT INTO nomes_femininos(nome) VALUES('Shirin');
INSERT INTO nomes_femininos(nome) VALUES('Soraya');
INSERT INTO nomes_femininos(nome) VALUES('Tahmineh');
INSERT INTO nomes_femininos(nome) VALUES('Taraneh');
INSERT INTO nomes_femininos(nome) VALUES('Yasmin');
INSERT INTO nomes_femininos(nome) VALUES('Yas');
INSERT INTO nomes_femininos(nome) VALUES('Zahra');
INSERT INTO nomes_femininos(nome) VALUES('Zara');
INSERT INTO nomes_femininos(nome) VALUES('Ziba');
INSERT INTO nomes_femininos(nome) VALUES('Aria');
INSERT INTO nomes_femininos(nome) VALUES('Aryana');
INSERT INTO nomes_femininos(nome) VALUES('Azadeh');
INSERT INTO nomes_femininos(nome) VALUES('Azita');
INSERT INTO nomes_femininos(nome) VALUES('Darya');
INSERT INTO nomes_femininos(nome) VALUES('Elika');
INSERT INTO nomes_femininos(nome) VALUES('Farideh');
INSERT INTO nomes_femininos(nome) VALUES('Hoda');
INSERT INTO nomes_femininos(nome) VALUES('Javaneh');
INSERT INTO nomes_femininos(nome) VALUES('Katayoun');
INSERT INTO nomes_femininos(nome) VALUES('Laleh');
INSERT INTO nomes_femininos(nome) VALUES('Mahin');
INSERT INTO nomes_femininos(nome) VALUES('Mahnoush');
INSERT INTO nomes_femininos(nome) VALUES('Mehrnaz');
INSERT INTO nomes_femininos(nome) VALUES('Mitra');
INSERT INTO nomes_femininos(nome) VALUES('Nargess');
INSERT INTO nomes_femininos(nome) VALUES('Nastaran');
INSERT INTO nomes_femininos(nome) VALUES('Niloufar');
INSERT INTO nomes_femininos(nome) VALUES('Pegah');
INSERT INTO nomes_femininos(nome) VALUES('Pooneh');
INSERT INTO nomes_femininos(nome) VALUES('Roshanak');
INSERT INTO nomes_femininos(nome) VALUES('Roya');
INSERT INTO nomes_femininos(nome) VALUES('Shahla');
INSERT INTO nomes_femininos(nome) VALUES('Sheida');
INSERT INTO nomes_femininos(nome) VALUES('Shokouh');
INSERT INTO nomes_femininos(nome) VALUES('Sholeh');
INSERT INTO nomes_femininos(nome) VALUES('Souzan');
INSERT INTO nomes_femininos(nome) VALUES('Vida');
INSERT INTO nomes_femininos(nome) VALUES('Zarrin');
INSERT INTO nomes_femininos(nome) VALUES('Zhaleh');
INSERT INTO nomes_femininos(nome) VALUES('Zohreh');
INSERT INTO nomes_femininos(nome) VALUES('Afsaneh');
INSERT INTO nomes_femininos(nome) VALUES('Afsoon');
INSERT INTO nomes_femininos(nome) VALUES('Anahita');
INSERT INTO nomes_femininos(nome) VALUES('Arghavan');
INSERT INTO nomes_femininos(nome) VALUES('Armaghan');
INSERT INTO nomes_femininos(nome) VALUES('Asal');
INSERT INTO nomes_femininos(nome) VALUES('Avin');
INSERT INTO nomes_femininos(nome) VALUES('Azin');
INSERT INTO nomes_femininos(nome) VALUES('Baran');
INSERT INTO nomes_femininos(nome) VALUES('Behnaz');
INSERT INTO nomes_femininos(nome) VALUES('Elnaz');
INSERT INTO nomes_femininos(nome) VALUES('Fariba');
INSERT INTO nomes_femininos(nome) VALUES('Fereshteh');
INSERT INTO nomes_femininos(nome) VALUES('Haleh');
INSERT INTO nomes_femininos(nome) VALUES('Hasti');
INSERT INTO nomes_femininos(nome) VALUES('Helia');
INSERT INTO nomes_femininos(nome) VALUES('Hengameh');
INSERT INTO nomes_femininos(nome) VALUES('Kamand');
INSERT INTO nomes_femininos(nome) VALUES('Kimia');
INSERT INTO nomes_femininos(nome) VALUES('Mahdieh');
INSERT INTO nomes_femininos(nome) VALUES('Mandana');
INSERT INTO nomes_femininos(nome) VALUES('Marzieh');
INSERT INTO nomes_femininos(nome) VALUES('Mehrnoush');
INSERT INTO nomes_femininos(nome) VALUES('Mona');
INSERT INTO nomes_femininos(nome) VALUES('Mozhdeh');
INSERT INTO nomes_femininos(nome) VALUES('Nassim');
INSERT INTO nomes_femininos(nome) VALUES('Niloofar');
INSERT INTO nomes_femininos(nome) VALUES('Parvaneh');
INSERT INTO nomes_femininos(nome) VALUES('Roxana');



INSERT INTO sobrenomes(sobrenome) VALUES('Golshifteh');
INSERT INTO sobrenomes(sobrenome) VALUES('Lykaios');
INSERT INTO sobrenomes(sobrenome) VALUES('Andreas');
INSERT INTO sobrenomes(sobrenome) VALUES('Antonopoulos');
INSERT INTO sobrenomes(sobrenome) VALUES('Bakirtzis');
INSERT INTO sobrenomes(sobrenome) VALUES('Christodoulou');
INSERT INTO sobrenomes(sobrenome) VALUES('Demetriou');
INSERT INTO sobrenomes(sobrenome) VALUES('Efstathiou');
INSERT INTO sobrenomes(sobrenome) VALUES('Fotiadis');
INSERT INTO sobrenomes(sobrenome) VALUES('Georgiou');
INSERT INTO sobrenomes(sobrenome) VALUES('Hatzis');
INSERT INTO sobrenomes(sobrenome) VALUES('Iordanou');
INSERT INTO sobrenomes(sobrenome) VALUES('Katsaros');
INSERT INTO sobrenomes(sobrenome) VALUES('Laskaris');
INSERT INTO sobrenomes(sobrenome) VALUES('Mavros');
INSERT INTO sobrenomes(sobrenome) VALUES('Nikolaidis');
INSERT INTO sobrenomes(sobrenome) VALUES('Oikonomou');
INSERT INTO sobrenomes(sobrenome) VALUES('Papadopoulos');
INSERT INTO sobrenomes(sobrenome) VALUES('Raptis');
INSERT INTO sobrenomes(sobrenome) VALUES('Samaras');
INSERT INTO sobrenomes(sobrenome) VALUES('Tzimas');
INSERT INTO sobrenomes(sobrenome) VALUES('Vasiliou');
INSERT INTO sobrenomes(sobrenome) VALUES('Zografos');
INSERT INTO sobrenomes(sobrenome) VALUES('Argyris');
INSERT INTO sobrenomes(sobrenome) VALUES('Bakogiannis');
INSERT INTO sobrenomes(sobrenome) VALUES('Christakis');
INSERT INTO sobrenomes(sobrenome) VALUES('Doukas');
INSERT INTO sobrenomes(sobrenome) VALUES('Eliopoulos');
INSERT INTO sobrenomes(sobrenome) VALUES('Fountas');
INSERT INTO sobrenomes(sobrenome) VALUES('Galanis');
INSERT INTO sobrenomes(sobrenome) VALUES('Hatzidakis');
INSERT INTO sobrenomes(sobrenome) VALUES('Ioannidis');
INSERT INTO sobrenomes(sobrenome) VALUES('Katsoulis');
INSERT INTO sobrenomes(sobrenome) VALUES('Livanios');
INSERT INTO sobrenomes(sobrenome) VALUES('Michalakis');
INSERT INTO sobrenomes(sobrenome) VALUES('Nikitas');
INSERT INTO sobrenomes(sobrenome) VALUES('Papageorgiou');
INSERT INTO sobrenomes(sobrenome) VALUES('Rousakis');
INSERT INTO sobrenomes(sobrenome) VALUES('Sotiropoulos');
INSERT INTO sobrenomes(sobrenome) VALUES('Tzakis');
INSERT INTO sobrenomes(sobrenome) VALUES('Vlastos');
INSERT INTO sobrenomes(sobrenome) VALUES('Zervos');
INSERT INTO sobrenomes(sobrenome) VALUES('Aghassian');
INSERT INTO sobrenomes(sobrenome) VALUES('Ardalan');
INSERT INTO sobrenomes(sobrenome) VALUES('Bahmani');
INSERT INTO sobrenomes(sobrenome) VALUES('Bakhtiar');
INSERT INTO sobrenomes(sobrenome) VALUES('Chamani');
INSERT INTO sobrenomes(sobrenome) VALUES('Darvish');
INSERT INTO sobrenomes(sobrenome) VALUES('Ehsani');
INSERT INTO sobrenomes(sobrenome) VALUES('Farzan');
INSERT INTO sobrenomes(sobrenome) VALUES('Ghaffari');
INSERT INTO sobrenomes(sobrenome) VALUES('Hedayat');
INSERT INTO sobrenomes(sobrenome) VALUES('Jahanshah');
INSERT INTO sobrenomes(sobrenome) VALUES('Karimi');
INSERT INTO sobrenomes(sobrenome) VALUES('Kaviani');
INSERT INTO sobrenomes(sobrenome) VALUES('Mehrabi');
INSERT INTO sobrenomes(sobrenome) VALUES('Nafisi');
INSERT INTO sobrenomes(sobrenome) VALUES('Parvizi');
INSERT INTO sobrenomes(sobrenome) VALUES('Qorbani');
INSERT INTO sobrenomes(sobrenome) VALUES('Rostami');
INSERT INTO sobrenomes(sobrenome) VALUES('Shahbazi');
INSERT INTO sobrenomes(sobrenome) VALUES('Tabrizi');
INSERT INTO sobrenomes(sobrenome) VALUES('Vaziri');
INSERT INTO sobrenomes(sobrenome) VALUES('Yazdani');
INSERT INTO sobrenomes(sobrenome) VALUES('Zamani');
INSERT INTO sobrenomes(sobrenome) VALUES('Amir');
INSERT INTO sobrenomes(sobrenome) VALUES('Behrouz');
INSERT INTO sobrenomes(sobrenome) VALUES('Chaman');
INSERT INTO sobrenomes(sobrenome) VALUES('Dehghan');
INSERT INTO sobrenomes(sobrenome) VALUES('Esmaili');
INSERT INTO sobrenomes(sobrenome) VALUES('Fard');
INSERT INTO sobrenomes(sobrenome) VALUES('Ganjavi');
INSERT INTO sobrenomes(sobrenome) VALUES('Hosseini');
INSERT INTO sobrenomes(sobrenome) VALUES('Jafari');
INSERT INTO sobrenomes(sobrenome) VALUES('Khodadadi');
INSERT INTO sobrenomes(sobrenome) VALUES('Latifi');
INSERT INTO sobrenomes(sobrenome) VALUES('Mahdavi');
INSERT INTO sobrenomes(sobrenome) VALUES('Nassiri');
INSERT INTO sobrenomes(sobrenome) VALUES('Pahlavi');
INSERT INTO sobrenomes(sobrenome) VALUES('Rahimi');
INSERT INTO sobrenomes(sobrenome) VALUES('Sadri');
INSERT INTO sobrenomes(sobrenome) VALUES('Tajik');
INSERT INTO sobrenomes(sobrenome) VALUES('Zadeh');
INSERT INTO sobrenomes(sobrenome) VALUES('Ahmadi');
INSERT INTO sobrenomes(sobrenome) VALUES('Ashrafi');
INSERT INTO sobrenomes(sobrenome) VALUES('Bakhtiari');
INSERT INTO sobrenomes(sobrenome) VALUES('Cheraghchi');
INSERT INTO sobrenomes(sobrenome) VALUES('Djahani');
INSERT INTO sobrenomes(sobrenome) VALUES('Ebrahimi');
INSERT INTO sobrenomes(sobrenome) VALUES('Fahimi');
INSERT INTO sobrenomes(sobrenome) VALUES('Golshani');
INSERT INTO sobrenomes(sobrenome) VALUES('Hassani');
INSERT INTO sobrenomes(sobrenome) VALUES('Isfahani');
INSERT INTO sobrenomes(sobrenome) VALUES('Jalali');
INSERT INTO sobrenomes(sobrenome) VALUES('Kazemi');
INSERT INTO sobrenomes(sobrenome) VALUES('Mokhtari');
INSERT INTO sobrenomes(sobrenome) VALUES('Nasiri');
INSERT INTO sobrenomes(sobrenome) VALUES('Pirooz');
INSERT INTO sobrenomes(sobrenome) VALUES('Rostamian');

INSERT INTO valores_5_a_10(valor) VALUES(5);
INSERT INTO valores_5_a_10(valor) VALUES(6);
INSERT INTO valores_5_a_10(valor) VALUES(7);
INSERT INTO valores_5_a_10(valor) VALUES(8);
INSERT INTO valores_5_a_10(valor) VALUES(9);
INSERT INTO valores_5_a_10(valor) VALUES(10);

INSERT INTO imagem_recruta_masculinos(caminho_imagem) VALUES('..\Imagens\Recrutas\recrutas\masculinos\1.bmp');
INSERT INTO imagem_recruta_masculinos(caminho_imagem) VALUES('..\Imagens\Recrutas\recrutas\masculinos\2.bmp');
INSERT INTO imagem_recruta_masculinos(caminho_imagem) VALUES('..\Imagens\Recrutas\recrutas\masculinos\3.bmp');
INSERT INTO imagem_recruta_masculinos(caminho_imagem) VALUES('..\Imagens\Recrutas\recrutas\masculinos\4.bmp');
INSERT INTO imagem_recruta_masculinos(caminho_imagem) VALUES('..\Imagens\Recrutas\recrutas\masculinos\5.bmp');
INSERT INTO imagem_recruta_femininos(caminho_imagem) VALUES('..\Imagens\Recrutas\recrutas\femininos\1.bmp');
INSERT INTO imagem_recruta_femininos(caminho_imagem) VALUES('..\Imagens\Recrutas\recrutas\femininos\2.bmp');
INSERT INTO imagem_recruta_femininos(caminho_imagem) VALUES('..\Imagens\Recrutas\recrutas\femininos\3.bmp');
INSERT INTO imagem_recruta_femininos(caminho_imagem) VALUES('..\Imagens\Recrutas\recrutas\femininos\4.bmp');
INSERT INTO imagem_recruta_femininos(caminho_imagem) VALUES('..\Imagens\Recrutas\recrutas\femininos\5.bmp');

INSERT INTO imagem_guerreiros_masculinos(caminho_imagem) VALUES('..\Imagens\Guerreiros\simples\masculinos\1.bmp');
INSERT INTO imagem_guerreiros_masculinos(caminho_imagem) VALUES('..\Imagens\Guerreiros\simples\masculinos\2.bmp');
INSERT INTO imagem_guerreiros_masculinos(caminho_imagem) VALUES('..\Imagens\Guerreiros\simples\masculinos\3.bmp');
INSERT INTO imagem_guerreiros_masculinos(caminho_imagem) VALUES('..\Imagens\Guerreiros\simples\masculinos\4.bmp');
INSERT INTO imagem_guerreiros_masculinos(caminho_imagem) VALUES('..\Imagens\Guerreiros\simples\masculinos\5.bmp');
INSERT INTO imagem_guerreiros_femininos(caminho_imagem) VALUES('..\Imagens\Guerreiros\simples\femininos\1.bmp');
INSERT INTO imagem_guerreiros_femininos(caminho_imagem) VALUES('..\Imagens\Guerreiros\simples\femininos\2.bmp');
INSERT INTO imagem_guerreiros_femininos(caminho_imagem) VALUES('..\Imagens\Guerreiros\simples\femininos\3.bmp');
INSERT INTO imagem_guerreiros_femininos(caminho_imagem) VALUES('..\Imagens\Guerreiros\simples\femininos\4.bmp');
INSERT INTO imagem_guerreiros_femininos(caminho_imagem) VALUES('..\Imagens\Guerreiros\simples\femininos\5.bmp');

INSERT INTO tipos_equipamentos(id, tipo) VALUES(1,'Arma');
INSERT INTO tipos_equipamentos(id, tipo) VALUES(2 ,'Escudo');
INSERT INTO tipos_equipamentos(id, tipo) VALUES(3 ,'Capacete');

INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Espada nível 1", 1, 0, 100, 80, '..\Imagens\Equipamentos\Armas\Espada_nivel_1.bmp', 1, 0, 1);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Espada nível 2", 2, 0, 200, 180, '..\Imagens\Equipamentos\Armas\Espada_nivel_2.bmp', 2, 0, 30);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Espada nível 3", 3, 0, 300, 280, '..\Imagens\Equipamentos\Armas\Espada_nivel_3.bmp', 3, 0, 50);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Espada nível 4", 4, 1, 400, 380, '..\Imagens\Equipamentos\Armas\Espada_nivel_4.bmp', 4, 0, 70);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Espada nível 5", 5, 2, 500, 500, '..\Imagens\Equipamentos\Armas\Espada_nivel_5.bmp', 5, 0, 100);

INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Lança nível 1", 1, 0, 80, 60, '..\Imagens\Equipamentos\Armas\Lanca_nivel_5.bmp', 1, 0, 1);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Lança nível 2", 2, 0, 180, 160, '..\Imagens\Equipamentos\Armas\Lanca_nivel_5.bmp', 2, 0, 25);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Lança nível 3", 3, 0, 280, 260, '..\Imagens\Equipamentos\Armas\Lanca_nivel_5.bmp', 3, 0, 50);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Lança nível 4", 4, 1, 380, 360, '..\Imagens\Equipamentos\Armas\Lanca_nivel_5.bmp', 4, 0, 60);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Lança nível 5", 5, 2, 480, 480, '..\Imagens\Equipamentos\Armas\Lanca_nivel_5.bmp', 5, 0, 80);

INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Machado nível 1", 1, 0, 90, 50, '..\Imagens\Equipamentos\Armas\Machado_nivel_5.bmp', 1, 0, 1);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Machado nível 2", 2, 0, 190, 150, '..\Imagens\Equipamentos\Armas\Machado_nivel_5.bmp', 2, 0, 28);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Machado nível 3", 3, 0, 290, 250, '..\Imagens\Equipamentos\Armas\Machado_nivel_5.bmp', 3, 0, 42);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Machado nível 4", 4, 1, 390, 350, '..\Imagens\Equipamentos\Armas\Machado_nivel_5.bmp', 4, 0, 60);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Machado nível 5", 5, 2, 490, 450, '..\Imagens\Equipamentos\Armas\Machado_nivel_5.bmp', 5, 0, 90);

INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Martelo nível 1", 1, 0, 110, 90, '..\Imagens\Equipamentos\Armas\Martelo_nivel_5.bmp', 1, 0, 1);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Martelo nível 2", 2, 0, 210, 190, '..\Imagens\Equipamentos\Armas\Martelo_nivel_5.bmp', 2, 0, 20);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Martelo nível 3", 3, 0, 310, 290, '..\Imagens\Equipamentos\Armas\Martelo_nivel_5.bmp', 3, 0, 40);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Martelo nível 4", 4, 1, 410, 390, '..\Imagens\Equipamentos\Armas\Martelo_nivel_5.bmp', 4, 0, 60);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(1, "Martelo nível 5", 5, 2, 510, 490, '..\Imagens\Equipamentos\Armas\Martelo_nivel_5.bmp', 5, 0, 80);

INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(2, "Escudo nível 1", 0, 1, 100, 90, '..\Imagens\Equipamentos\Escudos\Escudo_nivel_5.bmp', 1, 0, 1);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(2, "Escudo nível 2", 0, 2, 200, 190, '..\Imagens\Equipamentos\Escudos\Escudo_nivel_5.bmp', 2, 0, 20);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(2, "Escudo nível 3", 0, 3, 300, 290, '..\Imagens\Equipamentos\Escudos\Escudo_nivel_5.bmp', 3, 0, 40);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(2, "Escudo nível 4", 0, 4, 400, 390, '..\Imagens\Equipamentos\Escudos\Escudo_nivel_5.bmp', 4, 0, 60);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(2, "Escudo nível 5", 1, 5, 500, 490, '..\Imagens\Equipamentos\Escudos\Escudo_nivel_5.bmp', 5, 0, 80);
;
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(3, "Capacete nível 1", 0, 1, 100, 90, '..\Imagens\Equipamentos\Capacetes\Capacete_nivel_5.bmp', 1, 0, 1);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(3, "Capacete nível 2", 0, 2, 200, 190, '..\Imagens\Equipamentos\Capacetes\Capacete_nivel_5.bmp', 2, 0, 20);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(3, "Capacete nível 3", 0, 3, 300, 290, '..\Imagens\Equipamentos\Capacetes\Capacete_nivel_5.bmp', 3, 0, 40);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(3, "Capacete nível 4", 0, 4, 400, 390, '..\Imagens\Equipamentos\Capacetes\Capacete_nivel_5.bmp', 4, 0, 60);
INSERT INTO equipamentos(tipo, nome, ataque, defesa, preco_compra, preco_venda, caminho_imagem, nivel, status_equipamento, dias_jogados) VALUES(3, "Capacete nível 5", 1, 5, 500, 490, '..\Imagens\Equipamentos\Capacetes\Capacete_nivel_5.bmp', 5, 0, 80);